///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test_ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording7 recording.
    /// </summary>
    [TestModule("6ea39cfc-5c53-4620-b65e-6a5de47086c3", ModuleType.Recording, 1)]
    public partial class Recording7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the test_ranorexRepository repository.
        /// </summary>
        public static test_ranorexRepository repo = test_ranorexRepository.Instance;

        static Recording7 instance = new Recording7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeDivTag' at 1176;152.", repo.ApplicationUnderTest.SomeDivTagInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeDivTag.Click("1176;152");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvg' at 22;14.", repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvgInfo, new RecordItemIndex(2));
            repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvg.Click("22;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sepetim.BasketItemListZIxvtEditMode2M07yI.ButtonTagSil' at 183;19.", repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.ButtonTagSilInfo, new RecordItemIndex(4));
            repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.ButtonTagSil.Click("183;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvg' at 15;18.", repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvgInfo, new RecordItemIndex(5));
            repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvg.Click("15;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sepetim.BasketItemListZIxvtEditMode2M07yI.Path' at 8;2.", repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.PathInfo, new RecordItemIndex(6));
            repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.Path.Click("8;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvg' at 21;24.", repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvgInfo, new RecordItemIndex(7));
            repo.Sepetim.BasketItemListZIxvtEditMode2M07yI.WebElementSvg.Click("21;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1200 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(1200);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Sepetim.YourCartIsCurrentlyEmpty'.", repo.Sepetim.YourCartIsCurrentlyEmptyInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.Sepetim.YourCartIsCurrentlyEmptyInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
