///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test_ranorex
{
    public partial class Recording5
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_CartItemCount(RepoItemInfo spantagInfo)
        {
        	var cartItemCount = repo.ApplicationUnderTest.CartItemCount;
        	if(cartItemCount.Visible==true){
        		int cart_item_count=Int32.Parse(cartItemCount.InnerText);
        		if(cart_item_count>=1){
        			Report.Info(" user can add to cart one or more products.");
        		}
        	}
        	

        }

    }
}
