///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test_ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording4 recording.
    /// </summary>
    [TestModule("b7aa0008-5144-4884-b237-fb9617a543ee", ModuleType.Recording, 1)]
    public partial class Recording4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the test_ranorexRepository repository.
        /// </summary>
        public static test_ranorexRepository repo = test_ranorexRepository.Instance;

        static Recording4 instance = new Recording4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName' at 141;18.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(0));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName.Click("141;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 127;19.", repo.Dropdown.SelfInfo, new RecordItemIndex(1));
            repo.Dropdown.Self.Click("127;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin' at 180;24.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLoginInfo, new RecordItemIndex(2));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin.Click("180;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword' at 147;25.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(3));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.Click("147;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'SAso7ayeti10' with focus on 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(4));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.PressKeys("SAso7ayeti10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelect' at 164;22.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelectInfo, new RecordItemIndex(5));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelect.Click("164;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'ApplicationUnderTest.CıkışYap'.", repo.ApplicationUnderTest.CıkışYapInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.CıkışYapInfo, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ApplicationUnderTest.CıkışYap'.", repo.ApplicationUnderTest.CıkışYapInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.CıkışYapInfo, "Visible", "False");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
