///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test_ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording6 recording.
    /// </summary>
    [TestModule("f102290e-1642-469d-b179-7d24e97d4f1e", ModuleType.Recording, 1)]
    public partial class Recording6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the test_ranorexRepository repository.
        /// </summary>
        public static test_ranorexRepository repo = test_ranorexRepository.Instance;

        static Recording6 instance = new Recording6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording6()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording6 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AllMyLists' at 36;7.", repo.ApplicationUnderTest.AllMyListsInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.AllMyLists.Click("36;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyListAllHere' at 429;422.", repo.MyListAllHere.SelfInfo, new RecordItemIndex(1));
            repo.MyListAllHere.Self.Click("429;422");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyListAllHere.MyListLayout.CreateList' at 71;6.", repo.MyListAllHere.MyListLayout.CreateListInfo, new RecordItemIndex(2));
            repo.MyListAllHere.MyListLayout.CreateList.Click("71;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyListAllHere.MyListLayout.CreateListButton' at 138;16.", repo.MyListAllHere.MyListLayout.CreateListButtonInfo, new RecordItemIndex(3));
            repo.MyListAllHere.MyListLayout.CreateListButton.Click("138;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyListAllHere.MyListLayout.ListName' at 102;19.", repo.MyListAllHere.MyListLayout.ListNameInfo, new RecordItemIndex(5));
            repo.MyListAllHere.MyListLayout.ListName.Click("102;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'list1' with focus on 'MyListAllHere.MyListLayout.ListName'.", repo.MyListAllHere.MyListLayout.ListNameInfo, new RecordItemIndex(6));
            repo.MyListAllHere.MyListLayout.ListName.PressKeys("list1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyListAllHere.MyListLayout.Create' at 42;12.", repo.MyListAllHere.MyListLayout.CreateInfo, new RecordItemIndex(7));
            repo.MyListAllHere.MyListLayout.Create.Click("42;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyListAllHere.MyListLayout.WebElementSvg' at 10;9.", repo.MyListAllHere.MyListLayout.WebElementSvgInfo, new RecordItemIndex(8));
            repo.MyListAllHere.MyListLayout.WebElementSvg.Click("10;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
