///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test_ranorex
{
    public partial class Recording2
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void checkClickWhenEmpty()
        {
        	var txtUserName = repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName;
        	var error_msg = repo.UEyeGirişSayfasıUEyeOlHepsiburad.error_msg;
        	if(txtUserName.InnerText==""){
        		if(error_msg.Visible==true){
        			Report.Log(ReportLevel.Info, "Empty", "User name is empty");
        		}
        	}

        }

        public void Mouse_Click_BtnLogin(RepoItemInfo buttontagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttontagInfo' at 155;21.", buttontagInfo);
            buttontagInfo.FindAdapter<ButtonTag>().Click("155;21");
        }

    }
}
