///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test_ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("d23f268b-e51b-4bb8-bbbc-7ecca8e53947", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the test_ranorexRepository repository.
        /// </summary>
        public static test_ranorexRepository repo = test_ranorexRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 42;11.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("42;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Login' at 54;5.", repo.ApplicationUnderTest.LoginInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Login.Click("54;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLoginInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLoginInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.need_to_help'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.need_to_helpInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.need_to_helpInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.signup_div'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.signup_divInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.signup_divInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.signin_div'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.signin_divInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.signin_divInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
