///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test_ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the test_ranorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("19154c89-4b3d-4939-bf84-da4b6e0e6c07")]
    public partial class test_ranorexRepository : RepoGenBaseFolder
    {
        static test_ranorexRepository instance = new test_ranorexRepository();
        test_ranorexRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        test_ranorexRepositoryFolders.UEyeGirişSayfasıUEyeOlHepsiburadAppFolder _ueyegirişsayfasıueyeolhepsiburad;
        test_ranorexRepositoryFolders.DropdownAppFolder _dropdown;
        test_ranorexRepositoryFolders.SepetimAppFolder _sepetim;
        test_ranorexRepositoryFolders.DownloadsAppFolder _downloads;
        test_ranorexRepositoryFolders.MyListAllHereAppFolder _mylistallhere;

        /// <summary>
        /// Gets the singleton class instance representing the test_ranorexRepository element repository.
        /// </summary>
        [RepositoryFolder("19154c89-4b3d-4939-bf84-da4b6e0e6c07")]
        public static test_ranorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public test_ranorexRepository() 
            : base("test_ranorexRepository", "/", null, 0, false, "19154c89-4b3d-4939-bf84-da4b6e0e6c07", ".\\RepositoryImages\\test_ranorexRepository19154c89.rximgres")
        {
            _applicationundertest = new test_ranorexRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _ueyegirişsayfasıueyeolhepsiburad = new test_ranorexRepositoryFolders.UEyeGirişSayfasıUEyeOlHepsiburadAppFolder(this);
            _dropdown = new test_ranorexRepositoryFolders.DropdownAppFolder(this);
            _sepetim = new test_ranorexRepositoryFolders.SepetimAppFolder(this);
            _downloads = new test_ranorexRepositoryFolders.DownloadsAppFolder(this);
            _mylistallhere = new test_ranorexRepositoryFolders.MyListAllHereAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("19154c89-4b3d-4939-bf84-da4b6e0e6c07")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("bb18c679-32a9-484a-879d-f06f2b8bd8a2")]
        public virtual test_ranorexRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The UEyeGirişSayfasıUEyeOlHepsiburad folder.
        /// </summary>
        [RepositoryFolder("58c7b4c4-66de-4125-904f-93391349b9a0")]
        public virtual test_ranorexRepositoryFolders.UEyeGirişSayfasıUEyeOlHepsiburadAppFolder UEyeGirişSayfasıUEyeOlHepsiburad
        {
            get { return _ueyegirişsayfasıueyeolhepsiburad; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("2150472a-4da6-4e89-ab0e-76162b3c9e33")]
        public virtual test_ranorexRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The Sepetim folder.
        /// </summary>
        [RepositoryFolder("97d4b020-86cf-44b4-b334-45daace9a0bc")]
        public virtual test_ranorexRepositoryFolders.SepetimAppFolder Sepetim
        {
            get { return _sepetim; }
        }

        /// <summary>
        /// The Downloads folder.
        /// </summary>
        [RepositoryFolder("9b8242da-a6fa-458e-bcfd-378f4b555416")]
        public virtual test_ranorexRepositoryFolders.DownloadsAppFolder Downloads
        {
            get { return _downloads; }
        }

        /// <summary>
        /// The MyListAllHere folder.
        /// </summary>
        [RepositoryFolder("ca0d6313-c6a9-440d-9d48-3ad0227bca16")]
        public virtual test_ranorexRepositoryFolders.MyListAllHereAppFolder MyListAllHere
        {
            get { return _mylistallhere; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class test_ranorexRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("bb18c679-32a9-484a-879d-f06f2b8bd8a2")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _sepeteekle1Info;
            RepoItemInfo _cartitemcountInfo;
            RepoItemInfo _hesabımInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _allmylistsInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.hepsiburada.com']", parentFolder, 30000, null, false, "bb18c679-32a9-484a-879d-f06f2b8bd8a2", "")
            {
                _loginInfo = new RepoItemInfo(this, "Login", ".//a[#'login']", "", 30000, null, "9edb67c6-f1a9-4abe-9a0c-a1693aad9f77");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//div[#'myAccount']//ul/?/?/a[@innertext='Çıkış Yap']", "", 30000, null, "1e6c4897-e5c0-4f0b-8137-efae4aabee1b");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'myAccount']/?/?/span[@title='Giriş Yap']", "", 30000, null, "0720bea5-13c4-422d-853a-72856f1bacf4");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//div[#'container']//main/div/div/div[2]/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div/?/?/a[@title>'Samsung Galaxy A52 128 GB']/button[@innertext='Sepete ekle']", "", 30000, null, "22834db8-2cfe-485b-9bba-c236207fb73e");
                _sepeteekle1Info = new RepoItemInfo(this, "SepeteEkle1", ".//div[#'container']//main/div/div/div[2]/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div[3]/div/?/?/a[@title>'Are 2 Kutu Beyaz 100 adet']/button[@innertext='Sepete ekle']", "", 30000, null, "54c58de4-4324-43ae-a018-7b4ce2da219a");
                _cartitemcountInfo = new RepoItemInfo(this, "CartItemCount", ".//span[#'cartItemCount']", "", 30000, null, "1100c80a-c104-4e0d-8c33-d32f68be835e");
                _hesabımInfo = new RepoItemInfo(this, "Hesabım", ".//div[#'myAccount']//span[@innertext='Hesabım']", "", 30000, null, "54bc107b-49ad-4696-bdde-0c4ea8871575");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//div[#'container']/div/div", "", 30000, null, "f1b90f43-8c6d-4e10-a686-61c519f2fa3f");
                _allmylistsInfo = new RepoItemInfo(this, "AllMyLists", ".//div[#'myAccount']//ul/?/?/a[@title='All My Lists']/?/?/font[@innertext='All My Lists']", "", 30000, null, "cb534a71-9f61-47a0-ac00-5f7342aa1ac3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bb18c679-32a9-484a-879d-f06f2b8bd8a2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bb18c679-32a9-484a-879d-f06f2b8bd8a2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("9edb67c6-f1a9-4abe-9a0c-a1693aad9f77")]
            public virtual Ranorex.ATag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("9edb67c6-f1a9-4abe-9a0c-a1693aad9f77")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("1e6c4897-e5c0-4f0b-8137-efae4aabee1b")]
            public virtual Ranorex.ATag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("1e6c4897-e5c0-4f0b-8137-efae4aabee1b")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("0720bea5-13c4-422d-853a-72856f1bacf4")]
            public virtual Ranorex.SpanTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("0720bea5-13c4-422d-853a-72856f1bacf4")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("22834db8-2cfe-485b-9bba-c236207fb73e")]
            public virtual Ranorex.ButtonTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("22834db8-2cfe-485b-9bba-c236207fb73e")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle1 item.
            /// </summary>
            [RepositoryItem("54c58de4-4324-43ae-a018-7b4ce2da219a")]
            public virtual Ranorex.ButtonTag SepeteEkle1
            {
                get
                {
                    return _sepeteekle1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle1 item info.
            /// </summary>
            [RepositoryItemInfo("54c58de4-4324-43ae-a018-7b4ce2da219a")]
            public virtual RepoItemInfo SepeteEkle1Info
            {
                get
                {
                    return _sepeteekle1Info;
                }
            }

            /// <summary>
            /// The CartItemCount item.
            /// </summary>
            [RepositoryItem("1100c80a-c104-4e0d-8c33-d32f68be835e")]
            public virtual Ranorex.SpanTag CartItemCount
            {
                get
                {
                    return _cartitemcountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CartItemCount item info.
            /// </summary>
            [RepositoryItemInfo("1100c80a-c104-4e0d-8c33-d32f68be835e")]
            public virtual RepoItemInfo CartItemCountInfo
            {
                get
                {
                    return _cartitemcountInfo;
                }
            }

            /// <summary>
            /// The Hesabım item.
            /// </summary>
            [RepositoryItem("54bc107b-49ad-4696-bdde-0c4ea8871575")]
            public virtual Ranorex.SpanTag Hesabım
            {
                get
                {
                    return _hesabımInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Hesabım item info.
            /// </summary>
            [RepositoryItemInfo("54bc107b-49ad-4696-bdde-0c4ea8871575")]
            public virtual RepoItemInfo HesabımInfo
            {
                get
                {
                    return _hesabımInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("f1b90f43-8c6d-4e10-a686-61c519f2fa3f")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("f1b90f43-8c6d-4e10-a686-61c519f2fa3f")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The AllMyLists item.
            /// </summary>
            [RepositoryItem("cb534a71-9f61-47a0-ac00-5f7342aa1ac3")]
            public virtual Ranorex.FontTag AllMyLists
            {
                get
                {
                    return _allmylistsInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The AllMyLists item info.
            /// </summary>
            [RepositoryItemInfo("cb534a71-9f61-47a0-ac00-5f7342aa1ac3")]
            public virtual RepoItemInfo AllMyListsInfo
            {
                get
                {
                    return _allmylistsInfo;
                }
            }
        }

        /// <summary>
        /// The UEyeGirişSayfasıUEyeOlHepsiburadAppFolder folder.
        /// </summary>
        [RepositoryFolder("58c7b4c4-66de-4125-904f-93391349b9a0")]
        public partial class UEyeGirişSayfasıUEyeOlHepsiburadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _need_to_helpInfo;
            RepoItemInfo _signup_divInfo;
            RepoItemInfo _signin_divInfo;
            RepoItemInfo _error_msgInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnemailselectInfo;

            /// <summary>
            /// Creates a new UEyeGirişSayfasıUEyeOlHepsiburad  folder.
            /// </summary>
            public UEyeGirişSayfasıUEyeOlHepsiburadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UEyeGirişSayfasıUEyeOlHepsiburad", "/dom[@domain='giris.hepsiburada.com']", parentFolder, 30000, null, false, "58c7b4c4-66de-4125-904f-93391349b9a0", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", ".//input[#'txtUserName']", "", 30000, null, "1d1c3b50-40bd-433f-942e-eb7bd0ff73ae");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//button[#'btnLogin']", "", 30000, null, "d29386dd-fe1b-4594-b1c0-986d95773159");
                _need_to_helpInfo = new RepoItemInfo(this, "need_to_help", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/span[@innertext='Yardıma ihtiyacım var']", "", 30000, null, "4a6e3aa0-a1aa-4f15-91e6-e4e9d6b5e706");
                _signup_divInfo = new RepoItemInfo(this, "signup_div", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[1]/?/?/div[@innertext='Üye ol']", "", 30000, null, "61c99f94-ea22-4caf-a6d1-22566e23c32a");
                _signin_divInfo = new RepoItemInfo(this, "signin_div", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[1]/?/?/div[@innertext='Giriş yap']", "", 30000, null, "4aa53b42-6603-4bc5-bc48-94ac9b3eb62f");
                _error_msgInfo = new RepoItemInfo(this, "error_msg", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[2]//form[@action='https://giris.hepsiburada.com/?ReturnUrl=https%3A%2F%2Foauth.hepsiburada.com%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSPA%26redirect_uri%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252Fuyelik%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3D2f4341e507a14571b1a79086078f7a83%26code_challenge%3D3Tg8FP3iX5Ty1Je-OiUwRz6fUmn2IhUgZ0vSeEESnXI%26code_challenge_method%3DS256%26response_mode%3Dquery%26ActivePage%3DPURE_LOGIN%26oidcReturnUrl%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252F']/div/?/?/div[@innertext>'E-posta adresinizi veya telefon']", "", 30000, null, "47489660-04b6-4552-8fc1-1414604721e8");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//form[#'frmNewLogin']//input[@id='txtPassword']", "", 30000, null, "fbaf0012-8440-42c8-8c27-ee5a55faa0a5");
                _btnemailselectInfo = new RepoItemInfo(this, "BtnEmailSelect", ".//button[#'btnEmailSelect']", "", 30000, null, "76b09789-c44d-4e62-b9e7-970e7267a93d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("58c7b4c4-66de-4125-904f-93391349b9a0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("58c7b4c4-66de-4125-904f-93391349b9a0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("1d1c3b50-40bd-433f-942e-eb7bd0ff73ae")]
            public virtual Ranorex.InputTag TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("1d1c3b50-40bd-433f-942e-eb7bd0ff73ae")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("d29386dd-fe1b-4594-b1c0-986d95773159")]
            public virtual Ranorex.ButtonTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("d29386dd-fe1b-4594-b1c0-986d95773159")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The need_to_help item.
            /// </summary>
            [RepositoryItem("4a6e3aa0-a1aa-4f15-91e6-e4e9d6b5e706")]
            public virtual Ranorex.SpanTag need_to_help
            {
                get
                {
                    return _need_to_helpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The need_to_help item info.
            /// </summary>
            [RepositoryItemInfo("4a6e3aa0-a1aa-4f15-91e6-e4e9d6b5e706")]
            public virtual RepoItemInfo need_to_helpInfo
            {
                get
                {
                    return _need_to_helpInfo;
                }
            }

            /// <summary>
            /// The signup_div item.
            /// </summary>
            [RepositoryItem("61c99f94-ea22-4caf-a6d1-22566e23c32a")]
            public virtual Ranorex.DivTag signup_div
            {
                get
                {
                    return _signup_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The signup_div item info.
            /// </summary>
            [RepositoryItemInfo("61c99f94-ea22-4caf-a6d1-22566e23c32a")]
            public virtual RepoItemInfo signup_divInfo
            {
                get
                {
                    return _signup_divInfo;
                }
            }

            /// <summary>
            /// The signin_div item.
            /// </summary>
            [RepositoryItem("4aa53b42-6603-4bc5-bc48-94ac9b3eb62f")]
            public virtual Ranorex.DivTag signin_div
            {
                get
                {
                    return _signin_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The signin_div item info.
            /// </summary>
            [RepositoryItemInfo("4aa53b42-6603-4bc5-bc48-94ac9b3eb62f")]
            public virtual RepoItemInfo signin_divInfo
            {
                get
                {
                    return _signin_divInfo;
                }
            }

            /// <summary>
            /// The error_msg item.
            /// </summary>
            [RepositoryItem("47489660-04b6-4552-8fc1-1414604721e8")]
            public virtual Ranorex.DivTag error_msg
            {
                get
                {
                    return _error_msgInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The error_msg item info.
            /// </summary>
            [RepositoryItemInfo("47489660-04b6-4552-8fc1-1414604721e8")]
            public virtual RepoItemInfo error_msgInfo
            {
                get
                {
                    return _error_msgInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("fbaf0012-8440-42c8-8c27-ee5a55faa0a5")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("fbaf0012-8440-42c8-8c27-ee5a55faa0a5")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnEmailSelect item.
            /// </summary>
            [RepositoryItem("76b09789-c44d-4e62-b9e7-970e7267a93d")]
            public virtual Ranorex.ButtonTag BtnEmailSelect
            {
                get
                {
                    return _btnemailselectInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnEmailSelect item info.
            /// </summary>
            [RepositoryItemInfo("76b09789-c44d-4e62-b9e7-970e7267a93d")]
            public virtual RepoItemInfo BtnEmailSelectInfo
            {
                get
                {
                    return _btnemailselectInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("2150472a-4da6-4e89-ab0e-76162b3c9e33")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "2150472a-4da6-4e89-ab0e-76162b3c9e33", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2150472a-4da6-4e89-ab0e-76162b3c9e33")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2150472a-4da6-4e89-ab0e-76162b3c9e33")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The SepetimAppFolder folder.
        /// </summary>
        [RepositoryFolder("97d4b020-86cf-44b4-b334-45daace9a0bc")]
        public partial class SepetimAppFolder : RepoGenBaseFolder
        {
            test_ranorexRepositoryFolders.BasketItemListZIxvtEditMode2M07yIFolder _basketitemlistzixvteditmode2m07yi;
            RepoItemInfo _yourcartiscurrentlyemptyInfo;

            /// <summary>
            /// Creates a new Sepetim  folder.
            /// </summary>
            public SepetimAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Sepetim", "/dom[@domain='checkout.hepsiburada.com']", parentFolder, 30000, null, false, "97d4b020-86cf-44b4-b334-45daace9a0bc", "")
            {
                _basketitemlistzixvteditmode2m07yi = new test_ranorexRepositoryFolders.BasketItemListZIxvtEditMode2M07yIFolder(this);
                _yourcartiscurrentlyemptyInfo = new RepoItemInfo(this, "YourCartIsCurrentlyEmpty", ".//div[#'app']/div/div/div[2]/div/div[2]/div[1]/div[2]//font[@innertext>'Your cart is currently em']", "", 30000, null, "0aec75ce-069c-4e84-84cf-5effbc235704");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97d4b020-86cf-44b4-b334-45daace9a0bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97d4b020-86cf-44b4-b334-45daace9a0bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YourCartIsCurrentlyEmpty item.
            /// </summary>
            [RepositoryItem("0aec75ce-069c-4e84-84cf-5effbc235704")]
            public virtual Ranorex.FontTag YourCartIsCurrentlyEmpty
            {
                get
                {
                    return _yourcartiscurrentlyemptyInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The YourCartIsCurrentlyEmpty item info.
            /// </summary>
            [RepositoryItemInfo("0aec75ce-069c-4e84-84cf-5effbc235704")]
            public virtual RepoItemInfo YourCartIsCurrentlyEmptyInfo
            {
                get
                {
                    return _yourcartiscurrentlyemptyInfo;
                }
            }

            /// <summary>
            /// The BasketItemListZIxvtEditMode2M07yI folder.
            /// </summary>
            [RepositoryFolder("11f72905-830a-4781-b465-af7373f22045")]
            public virtual test_ranorexRepositoryFolders.BasketItemListZIxvtEditMode2M07yIFolder BasketItemListZIxvtEditMode2M07yI
            {
                get { return _basketitemlistzixvteditmode2m07yi; }
            }
        }

        /// <summary>
        /// The BasketItemListZIxvtEditMode2M07yIFolder folder.
        /// </summary>
        [RepositoryFolder("11f72905-830a-4781-b465-af7373f22045")]
        public partial class BasketItemListZIxvtEditMode2M07yIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _webelementsvgInfo;
            RepoItemInfo _buttontagsilInfo;
            RepoItemInfo _pathInfo;

            /// <summary>
            /// Creates a new BasketItemListZIxvtEditMode2M07yI  folder.
            /// </summary>
            public BasketItemListZIxvtEditMode2M07yIFolder(RepoGenBaseFolder parentFolder) :
                    base("BasketItemListZIxvtEditMode2M07yI", ".//section[#'onboarding_item_list']/ul", parentFolder, 30000, null, false, "11f72905-830a-4781-b465-af7373f22045", "")
            {
                _webelementsvgInfo = new RepoItemInfo(this, "WebElementSvg", "li[1]/div/div/div[1]/div[2]/div[1]//tag[@tagname='svg']", "", 30000, null, "4892216d-6e31-4bd1-b0f4-886d74bf1360");
                _buttontagsilInfo = new RepoItemInfo(this, "ButtonTagSil", "li[1]/div/div/div[1]/div[3]//button[@innertext='Sil']", "", 30000, null, "c38ff7f0-ff20-4f73-b578-7ab46b73d1fa");
                _pathInfo = new RepoItemInfo(this, "Path", "li[1]/div[2]/div/div[1]/div[2]/div[1]//tag[@tagname='path']", "", 30000, null, "c36de984-ef1d-4c60-8bdd-eb65c1020027");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("11f72905-830a-4781-b465-af7373f22045")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("11f72905-830a-4781-b465-af7373f22045")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebElementSvg item.
            /// </summary>
            [RepositoryItem("4892216d-6e31-4bd1-b0f4-886d74bf1360")]
            public virtual Ranorex.WebElement WebElementSvg
            {
                get
                {
                    return _webelementsvgInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg item info.
            /// </summary>
            [RepositoryItemInfo("4892216d-6e31-4bd1-b0f4-886d74bf1360")]
            public virtual RepoItemInfo WebElementSvgInfo
            {
                get
                {
                    return _webelementsvgInfo;
                }
            }

            /// <summary>
            /// The ButtonTagSil item.
            /// </summary>
            [RepositoryItem("c38ff7f0-ff20-4f73-b578-7ab46b73d1fa")]
            public virtual Ranorex.ButtonTag ButtonTagSil
            {
                get
                {
                    return _buttontagsilInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagSil item info.
            /// </summary>
            [RepositoryItemInfo("c38ff7f0-ff20-4f73-b578-7ab46b73d1fa")]
            public virtual RepoItemInfo ButtonTagSilInfo
            {
                get
                {
                    return _buttontagsilInfo;
                }
            }

            /// <summary>
            /// The Path item.
            /// </summary>
            [RepositoryItem("c36de984-ef1d-4c60-8bdd-eb65c1020027")]
            public virtual Ranorex.WebElement Path
            {
                get
                {
                    return _pathInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path item info.
            /// </summary>
            [RepositoryItemInfo("c36de984-ef1d-4c60-8bdd-eb65c1020027")]
            public virtual RepoItemInfo PathInfo
            {
                get
                {
                    return _pathInfo;
                }
            }
        }

        /// <summary>
        /// The DownloadsAppFolder folder.
        /// </summary>
        [RepositoryFolder("9b8242da-a6fa-458e-bcfd-378f4b555416")]
        public partial class DownloadsAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Downloads  folder.
            /// </summary>
            public DownloadsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Downloads", "/form[@title='Downloads']", parentFolder, 30000, null, true, "9b8242da-a6fa-458e-bcfd-378f4b555416", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9b8242da-a6fa-458e-bcfd-378f4b555416")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9b8242da-a6fa-458e-bcfd-378f4b555416")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MyListAllHereAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca0d6313-c6a9-440d-9d48-3ad0227bca16")]
        public partial class MyListAllHereAppFolder : RepoGenBaseFolder
        {
            test_ranorexRepositoryFolders.MyListLayoutFolder _mylistlayout;

            /// <summary>
            /// Creates a new MyListAllHere  folder.
            /// </summary>
            public MyListAllHereAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyListAllHere", "/dom[@domain='listelerim.hepsiburada.com']", parentFolder, 30000, null, false, "ca0d6313-c6a9-440d-9d48-3ad0227bca16", "")
            {
                _mylistlayout = new test_ranorexRepositoryFolders.MyListLayoutFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca0d6313-c6a9-440d-9d48-3ad0227bca16")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca0d6313-c6a9-440d-9d48-3ad0227bca16")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyListLayout folder.
            /// </summary>
            [RepositoryFolder("46da1556-a1cb-4b63-9cbd-bdf1aed2c1d1")]
            public virtual test_ranorexRepositoryFolders.MyListLayoutFolder MyListLayout
            {
                get { return _mylistlayout; }
            }
        }

        /// <summary>
        /// The MyListLayoutFolder folder.
        /// </summary>
        [RepositoryFolder("46da1556-a1cb-4b63-9cbd-bdf1aed2c1d1")]
        public partial class MyListLayoutFolder : RepoGenBaseFolder
        {
            RepoItemInfo _webelementsvgInfo;
            RepoItemInfo _createlistbuttonInfo;
            RepoItemInfo _createlistInfo;
            RepoItemInfo _createInfo;
            RepoItemInfo _listnameInfo;

            /// <summary>
            /// Creates a new MyListLayout  folder.
            /// </summary>
            public MyListLayoutFolder(RepoGenBaseFolder parentFolder) :
                    base("MyListLayout", ".//div[#'root']/div/div/div[3]", parentFolder, 30000, null, false, "46da1556-a1cb-4b63-9cbd-bdf1aed2c1d1", "")
            {
                _webelementsvgInfo = new RepoItemInfo(this, "WebElementSvg", ".//button/tag[@tagname='svg']", "", 30000, null, "543b8e0e-7656-4680-ba0c-ed7bba0c3590");
                _createlistbuttonInfo = new RepoItemInfo(this, "CreateListButton", "div[2]/div/div[1]/div[3]//div[@id='createListButton']", "", 30000, null, "bf4322ba-4609-4dba-b7a4-17f1cbcd62bf");
                _createlistInfo = new RepoItemInfo(this, "CreateList", "div[2]/div/div[1]/div[3]//div[@id='createListButton']/?/?/font[@innertext='Create List']", "", 30000, null, "db510571-62f1-45d3-a9c1-0a06f946b3f2");
                _createInfo = new RepoItemInfo(this, "Create", "div[2]/div/div[1]/div[3]//form[@action='https://listelerim.hepsiburada.com/']/button/?/?/font[@innertext='Create']", "", 30000, null, "b075e980-b7dc-4014-890e-237151efa57b");
                _listnameInfo = new RepoItemInfo(this, "ListName", "div[2]/div/div[1]/div[3]//form[@action='https://listelerim.hepsiburada.com/']/div[2]//input[@id='listName']", "", 30000, null, "41507b16-8d6f-4dd8-9824-f25d8f318e30");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("46da1556-a1cb-4b63-9cbd-bdf1aed2c1d1")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("46da1556-a1cb-4b63-9cbd-bdf1aed2c1d1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebElementSvg item.
            /// </summary>
            [RepositoryItem("543b8e0e-7656-4680-ba0c-ed7bba0c3590")]
            public virtual Ranorex.WebElement WebElementSvg
            {
                get
                {
                    return _webelementsvgInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg item info.
            /// </summary>
            [RepositoryItemInfo("543b8e0e-7656-4680-ba0c-ed7bba0c3590")]
            public virtual RepoItemInfo WebElementSvgInfo
            {
                get
                {
                    return _webelementsvgInfo;
                }
            }

            /// <summary>
            /// The CreateListButton item.
            /// </summary>
            [RepositoryItem("bf4322ba-4609-4dba-b7a4-17f1cbcd62bf")]
            public virtual Ranorex.DivTag CreateListButton
            {
                get
                {
                    return _createlistbuttonInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CreateListButton item info.
            /// </summary>
            [RepositoryItemInfo("bf4322ba-4609-4dba-b7a4-17f1cbcd62bf")]
            public virtual RepoItemInfo CreateListButtonInfo
            {
                get
                {
                    return _createlistbuttonInfo;
                }
            }

            /// <summary>
            /// The CreateList item.
            /// </summary>
            [RepositoryItem("db510571-62f1-45d3-a9c1-0a06f946b3f2")]
            public virtual Ranorex.FontTag CreateList
            {
                get
                {
                    return _createlistInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The CreateList item info.
            /// </summary>
            [RepositoryItemInfo("db510571-62f1-45d3-a9c1-0a06f946b3f2")]
            public virtual RepoItemInfo CreateListInfo
            {
                get
                {
                    return _createlistInfo;
                }
            }

            /// <summary>
            /// The Create item.
            /// </summary>
            [RepositoryItem("b075e980-b7dc-4014-890e-237151efa57b")]
            public virtual Ranorex.FontTag Create
            {
                get
                {
                    return _createInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The Create item info.
            /// </summary>
            [RepositoryItemInfo("b075e980-b7dc-4014-890e-237151efa57b")]
            public virtual RepoItemInfo CreateInfo
            {
                get
                {
                    return _createInfo;
                }
            }

            /// <summary>
            /// The ListName item.
            /// </summary>
            [RepositoryItem("41507b16-8d6f-4dd8-9824-f25d8f318e30")]
            public virtual Ranorex.InputTag ListName
            {
                get
                {
                    return _listnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ListName item info.
            /// </summary>
            [RepositoryItemInfo("41507b16-8d6f-4dd8-9824-f25d8f318e30")]
            public virtual RepoItemInfo ListNameInfo
            {
                get
                {
                    return _listnameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
